### PR TITLE
Support specifying multiple GPUs for a Fly runner

### PR DESCRIPTION
**Pull request by jonatanklosko**
I tested that multiple GPUs can be attached using the Livebook Fly runtime.

I didn't test FLAME specifically yet, but this will be much easier once we merge this, since I can use `FLAME_GIT_REF`.

### CODE REVIEW

**Comment by chrismccord** [comment]
❤️❤️❤️🐥🔥

**Comment by jonatanklosko** [comment]
I tried testing but run into this:

```
** (BadFunctionError) function #Function<16.42875188/0 in FLAME.CodeSync.new/1> is invalid, likely because it points to an old version of the code
    (flame 0.2.0) lib/flame/code_sync.ex:186: FLAME.CodeSync.extract_packaged_stream/1
    (flame 0.2.0) lib/flame/code_sync.ex:186: FLAME.CodeSync.extract_packaged_stream/1
    (flame 0.2.0) lib/flame/runner.ex:312: anonymous fn/6 in FLAME.Runner.handle_call/3
    (flame 0.2.0) lib/flame/runner.ex:431: anonymous fn/3 in FLAME.Runner.remote_call/4
```

I am setting `FLAME_GIT_REF=9ee8fd8f5fc034e3cb89128d8aaa4cc1a13f55b0` for the runtime machine and doing `{:flame, github: "phoenixframework/flame", ref: "9ee8fd8f5fc034e3cb89128d8aaa4cc1a13f55b0"}` in `Mix.install/1`, so those should match be the same. @chrismccord did you run into this before?

**Comment by chrismccord** [comment]
Are you sure you restarted the runtime?

**Comment by jonatanklosko** [comment]
Yeah, I checked with `System.get_env("FLAME_GIT_REF")` that the env var was set properly.

**Comment by chrismccord** [comment]
Weird, it looks like it doesn't like the function reference from `extract_dir: Keyword.get(opts, :extract_dir, fn -> "/" end),`, but I have never seen this be an issue across dozens of shared git references.

**Pull request merged**
